//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Website.UtilityPages {
    
    
    public partial class Error {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Insight.Website.MasterPages.Main Master {
            get {
                return ((Insight.Website.MasterPages.Main)(base.Master));
            }
        }
    }
}
